Repository CMU-17313Q/nodebb-f24-logic-lords, pull requests merged in 2024-09, with the labels that each got.

#30 added front end button to submit anonymously (User Story 4)
  .gitignore
  dump.rdb
  node_modules/nodebb-plugin-composer-default/.eslintrc
  node_modules/nodebb-plugin-composer-default/.gitattributes
  node_modules/nodebb-plugin-composer-default/.jshintrc
  node_modules/nodebb-plugin-composer-default/LICENSE
  node_modules/nodebb-plugin-composer-default/README.md
  node_modules/nodebb-plugin-composer-default/controllers.js
  node_modules/nodebb-plugin-composer-default/library.js
  node_modules/nodebb-plugin-composer-default/package.json
  node_modules/nodebb-plugin-composer-default/plugin.json
  node_modules/nodebb-plugin-composer-default/screenshots/desktop.png
  node_modules/nodebb-plugin-composer-default/screenshots/mobile.png
  node_modules/nodebb-plugin-composer-default/static/lib/.eslintrc
  node_modules/nodebb-plugin-composer-default/static/lib/admin.js
  node_modules/nodebb-plugin-composer-default/static/lib/client.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/autocomplete.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/categoryList.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/controls.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/formatting.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/post-queue.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/preview.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/resize.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/scheduler.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/tags.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/uploads.js
  node_modules/nodebb-plugin-composer-default/static/scss/composer.scss
  node_modules/nodebb-plugin-composer-default/static/scss/page-compose.scss
  node_modules/nodebb-plugin-composer-default/static/scss/textcomplete.scss
  node_modules/nodebb-plugin-composer-default/static/scss/zen-mode.scss
  node_modules/nodebb-plugin-composer-default/static/templates/admin/plugins/composer-default.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/compose.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/modals/topic-scheduler.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-formatting.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-tags.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-write-preview.tpl
  node_modules/nodebb-plugin-composer-default/websockets.js
Labels: frontend

#31 Added report bug button with a corresponding form (User story 2)
  public/openapi/read.yaml
  public/src/client/report-bug.js
  src/controllers/index.js
  src/controllers/reportBug.js
  src/routes/index.js
  src/views/bug-report-form.tpl
Labels: enhancement, frontend, backend

#32 Created a database for buglog (user story 2)
  package 2.json
  pidfile 2
  public/openapi/components/schemas/BugLogObject.yaml
  public/openapi/read.yaml
  public/openapi/read/admin/dashboard/bug-logs.yaml
Labels: backend, Moderate effort

#37 Add backend logic for posting anonymously (User Story 4)
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  src/categories/create.js
  src/controllers/helpers.js
  src/topics/create.js
  src/user/uploads.js
Labels: enhancement, backend
